package constants

// Leagues

const LEAGUE_CFL = 4405
const LEAGUE_WNBA = 4516

var LEAGUES = []int{LEAGUE_CFL, LEAGUE_WNBA}

var LEAGUE_TEAMS = map[int][]int{
	LEAGUE_CFL: {
		TEAM_CFL_BC,
		TEAM_CFL_CGY,
		TEAM_CFL_EDM,
		TEAM_CFL_HAM,
		TEAM_CFL_MTL,
		TEAM_CFL_OTT,
		TEAM_CFL_SSK,
		TEAM_CFL_TOR,
		TEAM_CFL_WPG,
	},
	LEAGUE_WNBA: {
		TEAM_WNBA_ATL,
		TEAM_WNBA_CHI,
		TEAM_WNBA_CON,
		TEAM_WNBA_DAL,
		TEAM_WNBA_GSV,
		TEAM_WNBA_IND,
		TEAM_WNBA_LVA,
		TEAM_WNBA_LAS,
		TEAM_WNBA_MIN,
		TEAM_WNBA_NYL,
		TEAM_WNBA_PHX,
		TEAM_WNBA_SEA,
		TEAM_WNBA_WAS,
	},
}

// Teams

const TEAM_CFL_BC = 135006
const TEAM_CFL_CGY = 135007
const TEAM_CFL_EDM = 135008
const TEAM_CFL_HAM = 135002
const TEAM_CFL_MTL = 135003
const TEAM_CFL_OTT = 135004
const TEAM_CFL_SSK = 135009
const TEAM_CFL_TOR = 135005
const TEAM_CFL_WPG = 135010

const TEAM_WNBA_ATL = 136447
const TEAM_WNBA_CHI = 136440
const TEAM_WNBA_CON = 136445
const TEAM_WNBA_DAL = 136441
const TEAM_WNBA_GSV = 150722
const TEAM_WNBA_IND = 136439
const TEAM_WNBA_LVA = 136437
const TEAM_WNBA_LAS = 136443
const TEAM_WNBA_MIN = 136442
const TEAM_WNBA_NYL = 136438
const TEAM_WNBA_PHX = 136444
const TEAM_WNBA_SEA = 136448
const TEAM_WNBA_WAS = 136446

var TEAM_SHORT_NAMES = map[int]string{
	TEAM_CFL_BC:  "BC",
	TEAM_CFL_CGY: "CGY",
	TEAM_CFL_EDM: "EDM",
	TEAM_CFL_HAM: "HAM",
	TEAM_CFL_MTL: "MTL",
	TEAM_CFL_OTT: "OTT",
	TEAM_CFL_SSK: "SSK",
	TEAM_CFL_TOR: "TOR",
	TEAM_CFL_WPG: "WPG",

	TEAM_WNBA_ATL: "ATL",
	TEAM_WNBA_CHI: "CHI",
	TEAM_WNBA_CON: "CON",
	TEAM_WNBA_DAL: "DAL",
	TEAM_WNBA_GSV: "GSV",
	TEAM_WNBA_IND: "IND",
	TEAM_WNBA_LVA: "LVA",
	TEAM_WNBA_LAS: "LAS",
	TEAM_WNBA_MIN: "MIN",
	TEAM_WNBA_NYL: "NYL",
	TEAM_WNBA_PHX: "PHX",
	TEAM_WNBA_SEA: "SEA",
	TEAM_WNBA_WAS: "WAS",
}
