package constants

// Leagues

const LEAGUE_CFL = 4405
const LEAGUE_NHL = 4380
const LEAGUE_NFL = 4391
const LEAGUE_WNBA = 4516
const LEAGUE_MLS = 4346
const LEAGUE_NWSL = 4521

var LEAGUES = []int{LEAGUE_CFL, LEAGUE_NHL, LEAGUE_NFL, LEAGUE_WNBA, LEAGUE_MLS, LEAGUE_NWSL}

var LEAGUE_TEAMS = map[int][]int{
	LEAGUE_CFL: {
		TEAM_CFL_BC,
		TEAM_CFL_CGY,
		TEAM_CFL_EDM,
		TEAM_CFL_HAM,
		TEAM_CFL_MTL,
		TEAM_CFL_OTT,
		TEAM_CFL_SSK,
		TEAM_CFL_TOR,
		TEAM_CFL_WPG,
	},
	LEAGUE_NHL: {
		TEAM_NHL_ANA,
		TEAM_NHL_BOS,
		TEAM_NHL_BUF,
		TEAM_NHL_CGY,
		TEAM_NHL_CAR,
		TEAM_NHL_CHI,
		TEAM_NHL_COL,
		TEAM_NHL_CBJ,
		TEAM_NHL_DAL,
		TEAM_NHL_DET,
		TEAM_NHL_EDM,
		TEAM_NHL_FLA,
		TEAM_NHL_LAK,
		TEAM_NHL_MIN,
		TEAM_NHL_MTL,
		TEAM_NHL_NSH,
		TEAM_NHL_NJD,
		TEAM_NHL_NYI,
		TEAM_NHL_NYR,
		TEAM_NHL_OTT,
		TEAM_NHL_PHI,
		TEAM_NHL_PIT,
		TEAM_NHL_SJS,
		TEAM_NHL_SEA,
		TEAM_NHL_STL,
		TEAM_NHL_TBL,
		TEAM_NHL_TOR,
		TEAM_NHL_UTA,
		TEAM_NHL_VAN,
		TEAM_NHL_VGK,
		TEAM_NHL_WSH,
		TEAM_NHL_WPG,
	},
	LEAGUE_NFL: {
		TEAM_NFL_ARI,
		TEAM_NFL_ATL,
		TEAM_NFL_BAL,
		TEAM_NFL_BUF,
		TEAM_NFL_CAR,
		TEAM_NFL_CHI,
		TEAM_NFL_CIN,
		TEAM_NFL_CLE,
		TEAM_NFL_DAL,
		TEAM_NFL_DEN,
		TEAM_NFL_DET,
		TEAM_NFL_GB,
		TEAM_NFL_HOU,
		TEAM_NFL_IND,
		TEAM_NFL_JAX,
		TEAM_NFL_KC,
		TEAM_NFL_LV,
		TEAM_NFL_LAC,
		TEAM_NFL_LAR,
		TEAM_NFL_MIA,
		TEAM_NFL_MIN,
		TEAM_NFL_NE,
		TEAM_NFL_NO,
		TEAM_NFL_NYG,
		TEAM_NFL_NYJ,
		TEAM_NFL_PHI,
		TEAM_NFL_PIT,
		TEAM_NFL_SF,
		TEAM_NFL_SEA,
		TEAM_NFL_TB,
		TEAM_NFL_TEN,
		TEAM_NFL_WAS,
	},
	LEAGUE_WNBA: {
		TEAM_WNBA_ATL,
		TEAM_WNBA_CHI,
		TEAM_WNBA_CON,
		TEAM_WNBA_DAL,
		TEAM_WNBA_GSV,
		TEAM_WNBA_IND,
		TEAM_WNBA_LVA,
		TEAM_WNBA_LAS,
		TEAM_WNBA_MIN,
		TEAM_WNBA_NYL,
		TEAM_WNBA_PHX,
		TEAM_WNBA_SEA,
		TEAM_WNBA_WAS,
	},
	LEAGUE_MLS: {
		TEAM_MLS_ATL,
		TEAM_MLS_ATX,
		TEAM_MLS_CHI,
		TEAM_MLS_CIN,
		TEAM_MLS_CLB,
		TEAM_MLS_CLT,
		TEAM_MLS_COL,
		TEAM_MLS_DAL,
		TEAM_MLS_DC,
		TEAM_MLS_HOU,
		TEAM_MLS_LA,
		TEAM_MLS_LAFC,
		TEAM_MLS_MIA,
		TEAM_MLS_MIN,
		TEAM_MLS_MTL,
		TEAM_MLS_NE,
		TEAM_MLS_NSH,
		TEAM_MLS_NYC,
		TEAM_MLS_ORL,
		TEAM_MLS_PHI,
		TEAM_MLS_POR,
		TEAM_MLS_RBNY,
		TEAM_MLS_RSL,
		TEAM_MLS_SEA,
		TEAM_MLS_SD,
		TEAM_MLS_SJ,
		TEAM_MLS_SKC,
		TEAM_MLS_STL,
		TEAM_MLS_TOR,
		TEAM_MLS_VAN,
	},
	LEAGUE_NWSL: {
		TEAM_NWSL_BAY,
		TEAM_NWSL_CHI,
		TEAM_NWSL_GFC,
		TEAM_NWSL_HOU,
		TEAM_NWSL_KC,
		TEAM_NWSL_LA,
		TEAM_NWSL_LOU,
		TEAM_NWSL_NC,
		TEAM_NWSL_ORL,
		TEAM_NWSL_POR,
		TEAM_NWSL_SD,
		TEAM_NWSL_SEA,
		TEAM_NWSL_UTA,
		TEAM_NWSL_WAS,
	},
}

// Teams

const TEAM_CFL_BC = 135006
const TEAM_CFL_CGY = 135007
const TEAM_CFL_EDM = 135008
const TEAM_CFL_HAM = 135002
const TEAM_CFL_MTL = 135003
const TEAM_CFL_OTT = 135004
const TEAM_CFL_SSK = 135009
const TEAM_CFL_TOR = 135005
const TEAM_CFL_WPG = 135010

const TEAM_NHL_ANA = 134846
const TEAM_NHL_BOS = 134830
const TEAM_NHL_BUF = 134831
const TEAM_NHL_CGY = 134848
const TEAM_NHL_CAR = 134838
const TEAM_NHL_CHI = 134854
const TEAM_NHL_COL = 134855
const TEAM_NHL_CBJ = 134839
const TEAM_NHL_DAL = 134856
const TEAM_NHL_DET = 134832
const TEAM_NHL_EDM = 134849
const TEAM_NHL_FLA = 134833
const TEAM_NHL_LAK = 134852
const TEAM_NHL_MIN = 134857
const TEAM_NHL_MTL = 134834
const TEAM_NHL_NSH = 134858
const TEAM_NHL_NJD = 134840
const TEAM_NHL_NYI = 134841
const TEAM_NHL_NYR = 134842
const TEAM_NHL_OTT = 134835
const TEAM_NHL_PHI = 134843
const TEAM_NHL_PIT = 134844
const TEAM_NHL_SJS = 134853
const TEAM_NHL_SEA = 140082
const TEAM_NHL_STL = 134859
const TEAM_NHL_TBL = 134836
const TEAM_NHL_TOR = 134837
const TEAM_NHL_UTA = 148494
const TEAM_NHL_VAN = 134850
const TEAM_NHL_VGK = 135913
const TEAM_NHL_WSH = 134845
const TEAM_NHL_WPG = 134851

const TEAM_NFL_ARI = 134946
const TEAM_NFL_ATL = 134942
const TEAM_NFL_BAL = 134922
const TEAM_NFL_BUF = 134918
const TEAM_NFL_CAR = 134943
const TEAM_NFL_CHI = 134938
const TEAM_NFL_CIN = 134923
const TEAM_NFL_CLE = 134924
const TEAM_NFL_DAL = 134934
const TEAM_NFL_DEN = 134930
const TEAM_NFL_DET = 134939
const TEAM_NFL_GB = 134940
const TEAM_NFL_HOU = 134926
const TEAM_NFL_IND = 134927
const TEAM_NFL_JAX = 134928
const TEAM_NFL_KC = 134931
const TEAM_NFL_LV = 134932
const TEAM_NFL_LAC = 135908
const TEAM_NFL_LAR = 135907
const TEAM_NFL_MIA = 134919
const TEAM_NFL_MIN = 134941
const TEAM_NFL_NE = 134920
const TEAM_NFL_NO = 134944
const TEAM_NFL_NYG = 134935
const TEAM_NFL_NYJ = 134921
const TEAM_NFL_PHI = 134936
const TEAM_NFL_PIT = 134925
const TEAM_NFL_SF = 134948
const TEAM_NFL_SEA = 134949
const TEAM_NFL_TB = 134945
const TEAM_NFL_TEN = 134929
const TEAM_NFL_WAS = 134937

const TEAM_WNBA_ATL = 136447
const TEAM_WNBA_CHI = 136440
const TEAM_WNBA_CON = 136445
const TEAM_WNBA_DAL = 136441
const TEAM_WNBA_GSV = 150722
const TEAM_WNBA_IND = 136439
const TEAM_WNBA_LVA = 136437
const TEAM_WNBA_LAS = 136443
const TEAM_WNBA_MIN = 136442
const TEAM_WNBA_NYL = 136438
const TEAM_WNBA_PHX = 136444
const TEAM_WNBA_SEA = 136448
const TEAM_WNBA_WAS = 136446

const TEAM_MLS_ATL = 135851
const TEAM_MLS_ATX = 140079
const TEAM_MLS_CHI = 134154
const TEAM_MLS_CIN = 136688
const TEAM_MLS_CLB = 134152
const TEAM_MLS_CLT = 140078
const TEAM_MLS_COL = 134794
const TEAM_MLS_DAL = 134146
const TEAM_MLS_DC = 134145
const TEAM_MLS_HOU = 134144
const TEAM_MLS_LA = 134153
const TEAM_MLS_LAFC = 136050
const TEAM_MLS_MIA = 137699
const TEAM_MLS_MIN = 135852
const TEAM_MLS_MTL = 134150
const TEAM_MLS_NE = 134159
const TEAM_MLS_NSH = 137700
const TEAM_MLS_NYC = 134630
const TEAM_MLS_ORL = 135292
const TEAM_MLS_PHI = 134142
const TEAM_MLS_POR = 134155
const TEAM_MLS_RBNY = 134156
const TEAM_MLS_RSL = 134158
const TEAM_MLS_SEA = 134149
const TEAM_MLS_SD = 150261
const TEAM_MLS_SJ = 134157
const TEAM_MLS_SKC = 134143
const TEAM_MLS_STL = 147062
const TEAM_MLS_TOR = 134148
const TEAM_MLS_VAN = 134147

const TEAM_NWSL_BAY = 147853
const TEAM_NWSL_CHI = 136427
const TEAM_NWSL_GFC = 136422
const TEAM_NWSL_HOU = 136436
const TEAM_NWSL_KC = 142126
const TEAM_NWSL_LA = 145093
const TEAM_NWSL_LOU = 142125
const TEAM_NWSL_NC = 136421
const TEAM_NWSL_ORL = 136425
const TEAM_NWSL_POR = 136426
const TEAM_NWSL_SD = 145094
const TEAM_NWSL_SEA = 136424
const TEAM_NWSL_UTA = 136428
const TEAM_NWSL_WAS = 136423

var TEAM_SHORT_NAMES = map[int]string{
	TEAM_CFL_BC:  "BC",
	TEAM_CFL_CGY: "CGY",
	TEAM_CFL_EDM: "EDM",
	TEAM_CFL_HAM: "HAM",
	TEAM_CFL_MTL: "MTL",
	TEAM_CFL_OTT: "OTT",
	TEAM_CFL_SSK: "SSK",
	TEAM_CFL_TOR: "TOR",
	TEAM_CFL_WPG: "WPG",

	TEAM_NHL_ANA: "ANA",
	TEAM_NHL_BOS: "BOS",
	TEAM_NHL_BUF: "BUF",
	TEAM_NHL_CGY: "CGY",
	TEAM_NHL_CAR: "CAR",
	TEAM_NHL_CHI: "CHI",
	TEAM_NHL_COL: "COL",
	TEAM_NHL_CBJ: "CBJ",
	TEAM_NHL_DAL: "DAL",
	TEAM_NHL_DET: "DET",
	TEAM_NHL_EDM: "EDM",
	TEAM_NHL_FLA: "FLA",
	TEAM_NHL_LAK: "LAK",
	TEAM_NHL_MIN: "MIN",
	TEAM_NHL_MTL: "MTL",
	TEAM_NHL_NSH: "NSH",
	TEAM_NHL_NJD: "NJD",
	TEAM_NHL_NYI: "NYI",
	TEAM_NHL_NYR: "NYR",
	TEAM_NHL_OTT: "OTT",
	TEAM_NHL_PHI: "PHI",
	TEAM_NHL_PIT: "PIT",
	TEAM_NHL_SJS: "SJS",
	TEAM_NHL_SEA: "SEA",
	TEAM_NHL_STL: "STL",
	TEAM_NHL_TBL: "TBL",
	TEAM_NHL_TOR: "TOR",
	TEAM_NHL_UTA: "UTA",
	TEAM_NHL_VAN: "VAN",
	TEAM_NHL_VGK: "VGK",
	TEAM_NHL_WSH: "WSH",
	TEAM_NHL_WPG: "WPG",

	TEAM_NFL_ARI: "ARI",
	TEAM_NFL_ATL: "ATL",
	TEAM_NFL_BAL: "BAL",
	TEAM_NFL_BUF: "BUF",
	TEAM_NFL_CAR: "CAR",
	TEAM_NFL_CHI: "CHI",
	TEAM_NFL_CIN: "CIN",
	TEAM_NFL_CLE: "CLE",
	TEAM_NFL_DAL: "DAL",
	TEAM_NFL_DEN: "DEN",
	TEAM_NFL_DET: "DET",
	TEAM_NFL_GB:  "GB",
	TEAM_NFL_HOU: "HOU",
	TEAM_NFL_IND: "IND",
	TEAM_NFL_JAX: "JAX",
	TEAM_NFL_KC:  "KC",
	TEAM_NFL_LV:  "LV",
	TEAM_NFL_LAC: "LAC",
	TEAM_NFL_LAR: "LAR",
	TEAM_NFL_MIA: "MIA",
	TEAM_NFL_MIN: "MIN",
	TEAM_NFL_NE:  "NE",
	TEAM_NFL_NO:  "NO",
	TEAM_NFL_NYG: "NYG",
	TEAM_NFL_NYJ: "NYJ",
	TEAM_NFL_PHI: "PHI",
	TEAM_NFL_PIT: "PIT",
	TEAM_NFL_SF:  "SF",
	TEAM_NFL_SEA: "SEA",
	TEAM_NFL_TB:  "TB",
	TEAM_NFL_TEN: "TEN",
	TEAM_NFL_WAS: "WAS",

	TEAM_WNBA_ATL: "ATL",
	TEAM_WNBA_CHI: "CHI",
	TEAM_WNBA_CON: "CON",
	TEAM_WNBA_DAL: "DAL",
	TEAM_WNBA_GSV: "GSV",
	TEAM_WNBA_IND: "IND",
	TEAM_WNBA_LVA: "LVA",
	TEAM_WNBA_LAS: "LAS",
	TEAM_WNBA_MIN: "MIN",
	TEAM_WNBA_NYL: "NYL",
	TEAM_WNBA_PHX: "PHX",
	TEAM_WNBA_SEA: "SEA",
	TEAM_WNBA_WAS: "WAS",

	TEAM_MLS_ATL:  "ATL",
	TEAM_MLS_ATX:  "ATX",
	TEAM_MLS_CHI:  "CHI",
	TEAM_MLS_CIN:  "CIN",
	TEAM_MLS_CLB:  "CLB",
	TEAM_MLS_CLT:  "CLT",
	TEAM_MLS_COL:  "COL",
	TEAM_MLS_DAL:  "DAL",
	TEAM_MLS_DC:   "DC",
	TEAM_MLS_HOU:  "HOU",
	TEAM_MLS_LA:   "LA",
	TEAM_MLS_LAFC: "LAFC",
	TEAM_MLS_MIA:  "MIA",
	TEAM_MLS_MIN:  "MIN",
	TEAM_MLS_MTL:  "MTL",
	TEAM_MLS_NE:   "NE",
	TEAM_MLS_NSH:  "NSH",
	TEAM_MLS_NYC:  "NYC",
	TEAM_MLS_ORL:  "ORL",
	TEAM_MLS_PHI:  "PHI",
	TEAM_MLS_POR:  "POR",
	TEAM_MLS_RBNY: "RBNY",
	TEAM_MLS_RSL:  "RSL",
	TEAM_MLS_SEA:  "SEA",
	TEAM_MLS_SD:   "SD",
	TEAM_MLS_SJ:   "SJ",
	TEAM_MLS_SKC:  "SKC",
	TEAM_MLS_STL:  "STL",
	TEAM_MLS_TOR:  "TOR",
	TEAM_MLS_VAN:  "VAN",

	TEAM_NWSL_BAY: "BAY",
	TEAM_NWSL_CHI: "CHI",
	TEAM_NWSL_GFC: "GFC",
	TEAM_NWSL_HOU: "HOU",
	TEAM_NWSL_KC:  "KC",
	TEAM_NWSL_LA:  "LA",
	TEAM_NWSL_LOU: "LOU",
	TEAM_NWSL_NC:  "NC",
	TEAM_NWSL_ORL: "ORL",
	TEAM_NWSL_POR: "POR",
	TEAM_NWSL_SD:  "SD",
	TEAM_NWSL_SEA: "SEA",
	TEAM_NWSL_UTA: "UTA",
	TEAM_NWSL_WAS: "WAS",
}
